name: Upload self-contained binaries

on:
  release:
    types: [published]

jobs:
  rust-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        platform: [x86_64]
        include:
          - os: ubuntu-24.04
            platform: x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup component add rustfmt
      - name: Build and upload artifact
        run: ./.github/workflows/build_binaries.sh ${{ matrix.os }} ${{ matrix.platform }} py-spy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}