name: Upload self-contained binaries

on:
  release:
    types: [published]

jobs:
  rust-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        platform: [x86_64]
        include:
          - os: ubuntu-20.04
            platform: x86_64
    container:
      image: ghcr.io/benfred/rust-musl-cross:x86_64-unknown-linux-musl
      env:
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - name: Build and upload artifact
        run: ./.github/workflows/build_binaries.sh ${{ matrix.os }} ${{ matrix.platform }} py-spy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}